### ISSUE TITLE
Discard button occasionally removes tokens from the game

### ISSUE THREAD

**Issue by vmullapudi1** [SaranSundar/GemRushServer#1]
When selecting tokens to take for a given turn and accidentally hitting discard tokens can be lost from the game, so instead of having 5 tokens for each gem color some of the tokens can be lost.
![image](https://user-images.githubusercontent.com/11009192/150700438-4aee8cfa-4420-4e1c-a32c-6a8022c8881d.png)

**Comment by juhwan-jeong-hub** [comment]
I'm sorry this game is dogshit. We are actively working on replacing our dogshit dev.

**Comment by SaranSundar** [comment]
Thanks, this issue has now been resolved.
